M48
; DRILL file {KiCad 9.0.0} date 2025-05-14T14:17:19+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-14T14:17:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X147.4Y-42.4
X147.4Y-63.6
X197.9Y-42.4
X197.9Y-63.6
M30
